set BUILD_TYPE=%1
IF "%BUILD_TYPE%"=="" set BUILD_TYPE=Release

set FEATHER_TK_API=GL_4_1
set FEATHER_TK_NFD=OFF
set FEATHER_TK_PYTHON=OFF
set FEATHER_TK_TESTS=ON
set FEATHER_TK_EXAMPLES=ON
set FEATHER_TK_GCOV=OFF

feather-tk\etc\Windows\windows-build-gha.bat %BUILD_TYPE%
